'use client';
import { useEffect,useMemo,useRef,useState } from 'react';
import { ArrowDown,Check,Leaf,RotateCcw,Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { questions,type Key } from '@/lib/questions';

const dims=[
 ['self','内省','内省','敏锐捕捉自己的情绪、动机与价值排序。','反复审视自己时，可能延迟行动。','独立判断、长期成长与价值一致的环境。',['生涯咨询','用户研究','内容策划']],
 ['people','人际','人际','读懂关系中的微妙信号，让人感到被理解。','容易过度照顾他人感受，忽略自己的边界。','高协作、需要理解用户或团队氛围的场景。',['人力资源','客户成功','心理服务']],
 ['create','创造','创造','生成、筛选并改进新想法，把零散线索组合成有效方案。','灵感很多时，可能低估收尾所需的耐心。','允许试错、重视原创提案和快速原型的团队。',['创意策划','产品经理','独立创作者']],
 ['aesthetic','美学','美学','对比例、氛围、质感和视觉一致性天然敏感。','可能因追求精致，对粗糙的第一版不够宽容。','重视体验与呈现质量、能持续打磨作品的场景。',['视觉设计','品牌策划','空间陈列']],
 ['language','语言','语言','用准确而有感染力的语言组织观点、传递感受。','表达顺畅不等于被接收，需要留意对方语境。','需要写作、演讲、叙事或跨团队沟通的工作。',['编辑文案','教师培训','公关传播']],
 ['logic','逻辑算法','逻辑','自然寻找规律、因果与更高效的解决路径。','面对模糊情绪时，可能太快进入解决问题模式。','目标清晰、信息充分、鼓励系统推演的环境。',['数据分析','策略运营','软件开发']],
 ['space','空间想象','空间','在脑中旋转、拆解与重构空间或复杂结构。','脑内画面很清楚时，容易省略对外说明步骤。','需要结构搭建、立体呈现或流程建模的任务。',['建筑设计','工业设计','游戏关卡']],
 ['nature','自然','自然','对环境、生命与细微变化保持持久好奇。','容易沉浸在观察里，需要主动把发现转成输出。','接触真实世界、重视长期观察与分类研究的场景。',['生态教育','园艺景观','食品研发']],
 ['body','身体-动觉','动觉','通过动作与亲身实践学习，手眼协调和现场感强。','纯文字和久坐环境可能让你的表现被低估。','允许动手验证、现场反馈快的任务。',['运动教练','手作设计','活动执行']],
 ['music','音乐','音乐','对节拍、音色与情绪起伏有独特捕捉力。','感受先行时，可能难以立刻解释判断依据。','声音、节奏或情绪氛围能成为素材的场景。',['音乐制作','声音设计','视频剪辑']]
] as const;
const keys=dims.map(d=>d[0]);
const personas:Record<Key,[string,string]>={self:['内在罗盘型','先听见自己，再选择值得走的路'],people:['关系共振型','从人与人的细微信号里找到答案'],create:['可能性发明型','本能地为旧问题打开一扇新门'],aesthetic:['感官造境型','让混乱获得质感、秩序与气氛'],language:['叙事点灯型','用语言照亮经验，也让他人看见'],logic:['系统解题型','把复杂世界拆成可以推进的路径'],space:['空间构筑型','先在脑中看见结构，再让它落地'],nature:['万物观察型','在真实世界的变化里发现规律'],body:['行动校准型','用双手、身体与现场反馈认识世界'],music:['节奏感应型','对声音、情绪和时间的起伏格外敏锐']};
const development:Record<Key,[string,string,string]>={self:['需要独立判断、深度思考的任务','从复盘与咨询类小项目积累案例','决策框架与自我管理能力'],people:['高互动、能持续获得人际反馈的任务','从访谈、社群或服务体验开始','信任建立与关系协调能力'],create:['目标明确但路径开放的创新任务','每周完成一个可展示的小原型','创意方法与作品组合'],aesthetic:['重视体验、允许反复打磨的任务','建立视觉观察库并做一次改造','风格判断与品质控制能力'],language:['需要写作、讲述或知识转译的任务','持续发布短文、讲解或采访作品','内容资产与表达影响力'],logic:['问题清晰、可验证迭代的任务','用真实数据完成一次分析项目','模型思维与自动化能力'],space:['涉及结构、布局或立体呈现的任务','完成一次空间、流程或信息建模','可视化与系统搭建能力'],nature:['接触真实环境、允许长期观察的任务','做一份连续七天的观察记录','分类研究与现场洞察能力'],body:['能动手、反馈快、少久坐的任务','报名一次实践课或参与现场执行','操作经验与即时判断能力'],music:['声音、节奏或情绪可成为材料的任务','完成一段声音、剪辑或节奏练习','听觉素材库与节奏控制能力']};
const childhood:Record<Key,string>={self:'小时候更愿意独处、写写画画，或反复琢磨“我真正怎么想”。',people:'很早就会观察气氛、照顾落单的人，也常成为朋友愿意倾诉的对象。',create:'会自行发明玩法、改造旧物，不满足于完全照着范本完成。',aesthetic:'对颜色、搭配、整洁度和画面是否舒服，有超出年龄的坚持。',language:'喜欢编故事、复述见闻、写日记，或能把一件小事讲得很生动。',logic:'喜欢规则、数字、谜题与输赢策略，常追问事情为什么这样运转。',space:'爱搭积木、画地图、摆放房间，能在脑中想象位置和结构。',nature:'容易被植物、动物、石头、天气和季节变化持续吸引。',body:'坐不住却能在运动、手工、拆装与模仿动作中快速学会。',music:'会反复哼唱、敲节拍、模仿声音，并对旋律与情绪变化敏感。'};

function Radar({values}:{values:number[]}){const p=(i:number,r:number)=>`${150+Math.cos(-Math.PI/2+i*Math.PI/5)*r},${150+Math.sin(-Math.PI/2+i*Math.PI/5)*r}`;return <svg viewBox="0 0 300 300" role="img" aria-label="十项天赋维度雷达图" className="radar">{[104,78,52,26].map(r=><polygon key={r} points={dims.map((_,i)=>p(i,r)).join(' ')} fill="none"/>)}{dims.map((d,i)=>{const [x,y]=p(i,132).split(',');return <text key={d[0]} x={x} y={+y+4} textAnchor="middle">{d[2]}</text>})}<polygon className="radar-fill" points={values.map((v,i)=>p(i,104*v/100)).join(' ')}/>{values.map((v,i)=>{const[x,y]=p(i,104*v/100).split(',');return <circle key={i} cx={x} cy={y} r="3"/>})}</svg>}

export default function Home(){
 const [stage,setStage]=useState<'home'|'quiz'|'result'>('home'),[active,setActive]=useState(0),[answers,setAnswers]=useState<number[]>([]);
 const sections=useRef<(HTMLElement|null)[]>([]),startedAt=useRef(Date.now()),identity=useRef({id:'',source:'direct'});
 const track=(eventName:string)=>{if(identity.current.id)void fetch('/api/track',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:identity.current.id,eventName,source:identity.current.source}),keepalive:true})};
 useEffect(()=>{let id=localStorage.getItem('weiguang_anonymous_id');if(!id){id=crypto.randomUUID();localStorage.setItem('weiguang_anonymous_id',id)}identity.current={id,source:new URLSearchParams(location.search).get('source')?.slice(0,80)||'direct'};track('page_view')},[]);
 const scores=useMemo(()=>{const raw=Object.fromEntries(keys.map(k=>[k,0])) as Record<Key,number>;answers.forEach((a,i)=>{if(a===undefined)return;Object.entries(questions[i].options[a].scores).forEach(([k,v])=>raw[k as Key]+=v||0)});const max=Math.max(...Object.values(raw),1);return dims.map(d=>Math.round(42+raw[d[0]]/max*54))},[answers]);
 const ranked=dims.map((d,i)=>({d,score:scores[i]})).sort((a,b)=>b.score-a.score),top=ranked.slice(0,3),low=ranked.slice(-2).reverse(),type=personas[top[0].d[0]][0],path=development[top[0].d[0]];
 const start=()=>{startedAt.current=Date.now();track('test_start');setStage('quiz');setTimeout(()=>scrollTo({top:0}),0)};
 const choose=(q:number,a:number)=>{const next=[...answers];next[q]=a;setAnswers(next);if([9,19,29].includes(q))track(`progress_${q+1}`);if(q===29){setTimeout(()=>setStage('result'),520);return}setActive(q+1);setTimeout(()=>sections.current[q+1]?.scrollIntoView({behavior:'smooth',block:'start'}),260)};
 const restart=()=>{track('restart_test');setAnswers([]);setActive(0);startedAt.current=Date.now();setStage('quiz');scrollTo({top:0})};
 useEffect(()=>{if(stage!=='result'||!identity.current.id)return;track('test_complete');track('report_view');void fetch('/api/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:identity.current.id,typeName:type,top:top.map(x=>x.d[1]),scores,durationSeconds:Math.round((Date.now()-startedAt.current)/1000)})})},[stage]);

 if(stage==='home')return <main className="shell autumn"><section className="hero hero-clean"><div className="eyebrow"><Sparkles/>30 个记忆与职业情境 · 约 6 分钟</div><h1>灵魂的欲望<br/>是命运的先知</h1><p className="lead">你小时候反复靠近的事，也许不是一时贪玩，而是某种能力最早发出的信号。找回那些被忽略的线索，看看你更适合在哪种工作世界里发力。</p><p className="manifesto">别再只用不擅长的方式证明自己。</p><Button onClick={start} className="primary-cta">找回我天生擅长的事 <ArrowDown/></Button><div className="talent-ribbon">{dims.map(d=><span key={d[0]}>{d[1]}</span>)}</div><div className="sun-print"><span>10</span><p>TALENT<br/>INSTINCTS</p>{['童年','本能','职业','路径'].map((x,i)=><i key={x} className={`seed s${i}`}>{x}</i>)}</div></section><footer>本测试用于自我探索与娱乐参考，不构成心理测量、科学诊断或职业结果保证。</footer></main>;

 if(stage==='quiz')return <main className="quiz-scroll"><header className="quiz-nav"><button onClick={()=>setStage('home')}>退出</button><div className="brand small"><span className="brand-mark"><Leaf/></span>拾光天赋</div><span>{Math.min(active+1,30)} / 30</span><div className="progress"><i style={{width:`${(active+1)/30*100}%`}}/></div></header><div className="question-stream">{questions.map((q,qi)=><section key={qi} ref={el=>{sections.current[qi]=el}} className={`question-panel ${qi===active?'is-active':''} ${answers[qi]!==undefined?'is-answered':''}`}><div className="question-inner"><p className="scene">{String(qi+1).padStart(2,'0')} · {q.scene}</p><h2>{q.title}</h2><p className="hint">凭第一反应选择，没有标准答案</p><div className="options">{q.options.map((o,oi)=><button key={oi} disabled={qi>active} className={answers[qi]===oi?'selected':''} onClick={()=>choose(qi,oi)}><span>{String.fromCharCode(65+oi)}</span><b>{o.text}</b><Check/></button>)}</div>{qi<29&&answers[qi]!==undefined&&<p className="continue"><ArrowDown/>下一段正在展开</p>}</div></section>)}</div></main>;

 return <main className="result-page autumn"><nav><div className="brand small"><span className="brand-mark"><Leaf/></span>拾光天赋</div><button className="restart" onClick={restart}><RotateCcw/>重新测试</button></nav><header className="result-hero"><p className="eyebrow">YOUR TALENT ARCHETYPE</p><h1>你的天赋人格<br/><em>「{type}」</em></h1><p className="persona-line">{personas[top[0].d[0]][1]}</p><p>你的优势链由 <b>{top[0].d[1]}</b> 发起，借助 <b>{top[1].d[1]}</b> 推进，再由 <b>{top[2].d[1]}</b> 放大。它不是唯一职业答案，而是一组可以迁移到不同领域的能力组合。</p><div className="top-three">{top.map((x,i)=><article key={x.d[0]}><span>核心天赋 {i+1}</span><b>{x.d[1]}</b><strong>{x.score}</strong></article>)}</div></header><section className="report"><div className="chart-card"><p className="section-kicker">能力全景</p><h2>十维天赋图谱</h2><Radar values={scores}/><div className="score-list">{dims.map((d,i)=><div key={d[0]}><span>{d[1]}</span><i><b style={{width:`${scores[i]}%`}}/></i><strong>{scores[i]}</strong></div>)}</div></div><div className="insight"><p className="section-kicker">你的第一驱动力</p><h2>{top[0].d[1]}</h2><p>{top[0].d[3]} 当它与{top[1].d[1]}结合，你更容易把别人忽略的线索，转化成可理解、可行动的方向。</p><div className="mini"><span>潜在盲点</span><p>{top[0].d[4]}</p></div><div className="mini"><span>适合工作场景</span><p>{top[0].d[5]}</p></div></div><div className="talent-story"><p className="section-kicker">童年留下的提示</p><h2>你可能很早就在这样使用天赋</h2><div className="story-grid">{top.map(x=><article key={x.d[0]}><b>{x.d[1]}</b><p>{childhood[x.d[0]]}</p></article>)}</div></div><div className="talent-detail"><p className="section-kicker">十大维度详解</p><h2>不只看排名，也看你如何使用它</h2><div className="detail-grid">{ranked.map(x=><article key={x.d[0]}><header><b>{x.d[1]}</b><strong>{x.score}</strong></header><p>{x.d[3]}</p></article>)}</div></div><div className="drain"><p className="section-kicker">隐性消耗提醒</p><h2>分数较低不等于没有能力</h2><p>你的 <b>{low[0].d[1]}</b> 与 <b>{low[1].d[1]}</b> 相对不占优势。这更可能意味着：长期依赖这些方式完成所有工作，需要你投入更多主动精力。选择职业时，可通过团队互补、工具和流程降低消耗，而不是给自己贴上“做不到”的标签。</p></div><div className="career"><p className="section-kicker">职业方向</p><h2>先靠近这些工作内容</h2><div className="career-tags">{Array.from(new Set(top.flatMap(x=>x.d[6]))).slice(0,6).map(j=><span key={j}>{j}</span>)}</div><p className="note">职业名称只是入口。真正需要验证的是：你是否喜欢它的日常任务、协作方式与成长代价。</p></div><div className="career-road"><p className="section-kicker">职业发展路线</p><h2>把天赋变成可被看见的能力</h2><div className="road-grid"><article><span>优先寻找</span><b>{path[0]}</b></article><article><span>起步实验</span><b>{path[1]}</b></article><article><span>长期资产</span><b>{path[2]}</b></article></div></div><div className="action"><p className="section-kicker">未来 7 天</p><h2>不要急着转行，先留下三枚证据</h2><ol><li><b>追溯童年线索</b><span>写下三件小时候没人要求，你也会反复去做的事。</span></li><li><b>完成最小实验</b><span>从推荐方向中选一个，做出一件可展示的小作品。</span></li><li><b>检查真实反馈</b><span>问两位熟悉你的人：我在哪类任务里最有生命力？</span></li></ol></div></section><footer className="result-footer"><p>别让一次测试替你决定人生，让真实行动替天赋留下证据。</p><button onClick={()=>setStage('home')}>回到首页</button></footer></main>;
}
