'use client';
import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Compass, RotateCcw, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';

const dims=[
 ['self','自我觉察','内省','#7DF2C1','敏锐捕捉自己的情绪、动机与价值排序。','反复审视自己时，可能延迟行动。','独立判断、长期成长与价值一致的环境。',['生涯咨询','用户研究','内容策划']],
 ['people','人际洞察','共情','#FFCF70','读懂关系中的微妙信号，让人感到被理解。','容易过度照顾他人感受，忽略自己的边界。','高协作、需要理解用户或团队氛围的场景。',['人力资源','客户成功','心理服务']],
 ['create','创造表达','创想','#F58DA8','把零散灵感重新组合，提出有辨识度的方案。','灵感很多时，可能低估收尾所需的耐心。','允许试错、重视原创提案和快速原型的团队。',['创意策划','产品经理','独立创作者']],
 ['aesthetic','审美感知','审美','#BC9CFF','对比例、氛围、质感和视觉一致性天然敏感。','可能因追求精致，对粗糙的第一版不够宽容。','重视体验与呈现质量、能持续打磨作品的场景。',['视觉设计','品牌策划','空间陈列']],
 ['language','语言表达','语言','#72C8FF','用准确而有感染力的语言组织观点、传递感受。','表达顺畅不等于被接收，需要留意对方语境。','需要写作、演讲、叙事或跨团队沟通的工作。',['编辑文案','教师培训','公关传播']],
 ['logic','逻辑分析','逻辑','#6EE7F2','自然寻找规律、因果与更高效的解决路径。','面对模糊情绪时，可能太快进入解决问题模式。','目标清晰、信息充分、鼓励系统推演的环境。',['数据分析','策略运营','软件开发']],
 ['space','空间想象','空间','#9BB8FF','在脑中旋转、拆解与重构空间或复杂结构。','脑内画面很清楚时，容易省略对外说明步骤。','需要结构搭建、立体呈现或流程建模的任务。',['建筑设计','工业设计','游戏关卡']],
 ['nature','自然观察','观察','#8BD17C','对环境、生命与细微变化保持持久好奇。','容易沉浸在观察里，需要主动把发现转成输出。','接触真实世界、重视长期观察与分类研究的场景。',['生态教育','园艺景观','食品研发']],
 ['body','身体动觉','动觉','#FF9E72','通过动作与亲身实践学习，手眼协调和现场感强。','纯文字和久坐环境可能让你的表现被低估。','允许动手验证、现场反馈快的任务。',['运动教练','手作设计','活动执行']],
 ['music','节奏音乐','节奏','#F2E56E','对节拍、音色与情绪起伏有独特捕捉力。','感受先行时，可能难以立刻解释判断依据。','声音、节奏或情绪氛围能成为素材的场景。',['音乐制作','声音设计','视频剪辑']]
] as const;
type Key=typeof dims[number][0]; type Option={text:string;scores:Partial<Record<Key,number>>};
const optionTexts=['先独自理清问题，再写下自己的判断','找人聊聊，从不同反应里寻找线索','换个新角度，先做一个有趣的小尝试','把信息分类比较，找出最合理的规律'];
const promptData=[['新任务突然出现','面对一个完全陌生的任务，你最自然的起手式是？'],['周末空出半天','没有安排的下午，你更容易被什么吸引？'],['团队意见僵持','大家争论不下时，你通常会怎么做？'],['收到复杂信息','面对一大堆材料，你最先注意到什么？'],['朋友情绪低落','对方说“我没事”时，你会倾向于？'],['布置一个空间','让房间更舒服，你会优先改变什么？'],['学习新技能','哪种学习方式最能让你快速上手？'],['走进陌生街区','你最可能记住沿途的什么？'],['准备一次分享','你最愿意负责其中哪个部分？'],['计划一趟旅行','制定路线时，你最享受哪一步？'],['看到一部好电影','结束后最容易留在你脑中的是？'],['遇到效率瓶颈','重复工作越来越慢，你会怎么处理？'],['参加多人聚会','进入陌生人较多的场合，你通常？'],['完成一个作品','什么瞬间最让你有满足感？'],['听到一首新歌','你下意识最先捕捉到什么？'],['面对重要选择','你更信任哪一种判断依据？'],['收到模糊需求','对方只说“做得高级一点”，你会？'],['整理桌面文件','你更可能采用哪种整理方式？'],['观察一场活动','你最容易发现哪个问题？'],['需要记住内容','哪种方法对你最有效？'],['策划一条内容','你会从哪个部分开始？'],['身处自然环境','你最想做的事是什么？'],['碰到动手任务','面对需要组装或操作的东西，你会？'],['解释复杂概念','你通常会怎样让别人听懂？'],['连续工作很久','哪种休息最能让你重新有能量？'],['评价一个产品','你最先判断它的哪一面？'],['临时上台发言','你最依赖什么完成表达？'],['看见一个趋势','你会如何确认它值得关注？'],['合作项目收尾','你最在意留下什么？'],['想象三年后的你','哪个画面最能让你感到期待？']];
const keys=dims.map(d=>d[0]);
const questions=promptData.map((p,i)=>({scene:p[0],title:p[1],options:optionTexts.map((text,j):Option=>({text,scores:{[keys[(i+j*2)%10]]:3,[keys[(i+j*2+3)%10]]:1}}))}));
const typeNames=['灵感编织者','清醒探索家','温柔连接者','秩序解码师','感知造境师','行动点火者'];

function Radar({values}:{values:number[]}){const point=(i:number,r:number)=>`${150+Math.cos(-Math.PI/2+i*Math.PI/5)*r},${150+Math.sin(-Math.PI/2+i*Math.PI/5)*r}`;return <svg viewBox="0 0 300 300" role="img" aria-label="十项天赋维度雷达图" className="radar">{[104,78,52,26].map(r=><polygon key={r} points={dims.map((_,i)=>point(i,r)).join(' ')} fill="none" stroke="rgba(255,255,255,.13)"/>)}{dims.map((d,i)=>{const [x,y]=point(i,132).split(',');return <text key={d[0]} x={x} y={+y+4} textAnchor="middle">{d[2]}</text>})}<polygon points={values.map((v,i)=>point(i,104*v/100)).join(' ')} fill="rgba(125,242,193,.22)" stroke="#7DF2C1" strokeWidth="2"/>{values.map((v,i)=>{const [x,y]=point(i,104*v/100).split(',');return <circle key={i} cx={x} cy={y} r="3" fill="#7DF2C1"/>})}</svg>}

export default function Home(){
 const [stage,setStage]=useState<'home'|'quiz'|'result'>('home'),[current,setCurrent]=useState(0),[answers,setAnswers]=useState<number[]>([]);
 const startedAt=useRef(Date.now()),identity=useRef({id:'',source:'direct'});
 const track=(eventName:string)=>{if(identity.current.id)void fetch('/api/track',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:identity.current.id,eventName,source:identity.current.source}),keepalive:true})};
 useEffect(()=>{let id=localStorage.getItem('weiguang_anonymous_id');if(!id){id=crypto.randomUUID();localStorage.setItem('weiguang_anonymous_id',id)}identity.current={id,source:new URLSearchParams(location.search).get('source')?.slice(0,80)||'direct'};track('page_view')},[]);
 const scores=useMemo(()=>{const raw=Object.fromEntries(keys.map(k=>[k,0])) as Record<Key,number>;answers.forEach((a,i)=>Object.entries(questions[i].options[a].scores).forEach(([k,v])=>raw[k as Key]+=v||0));const max=Math.max(...Object.values(raw),1);return dims.map(d=>Math.round(42+raw[d[0]]/max*54))},[answers]);
 const ranked=dims.map((d,i)=>({d,score:scores[i]})).sort((a,b)=>b.score-a.score),top=ranked.slice(0,3);
 const choose=(i:number)=>{const a=[...answers];a[current]=i;setAnswers(a);if([9,19,29].includes(current))track(`progress_${current+1}`);setTimeout(()=>current<29?setCurrent(current+1):setStage('result'),180)};
 const restart=()=>{track('restart_test');startedAt.current=Date.now();setAnswers([]);setCurrent(0);setStage('quiz');scrollTo({top:0,behavior:'smooth'})};
 useEffect(()=>{if(stage!=='result'||!identity.current.id)return;const t=dims.map((d,i)=>({d,score:scores[i]})).sort((a,b)=>b.score-a.score).slice(0,3),name=typeNames[(keys.indexOf(t[0].d[0])+keys.indexOf(t[1].d[0]))%typeNames.length];track('test_complete');track('report_view');void fetch('/api/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({anonymousId:identity.current.id,typeName:name,top:t.map(x=>x.d[1]),scores,durationSeconds:Math.round((Date.now()-startedAt.current)/1000)})})},[stage]);
 if(stage==='home')return <main className="shell"><nav><div className="brand"><span className="brand-mark">M</span>微光图谱</div><span className="nav-note">职业探索 · 轻量版</span></nav><section className="hero"><div className="eyebrow"><Sparkles size={15}/>30 道情境题 · 约 5 分钟</div><h1>你不是没有天赋，<br/><em>只是还没为它命名。</em></h1><p className="lead">从十种能力线索里，找到你最自然的优势组合。不是替你决定职业，而是给下一步探索一张更清晰的地图。</p><Button onClick={()=>{startedAt.current=Date.now();track('test_start');setStage('quiz')}} className="primary-cta">开始发现我的天赋 <ArrowRight/></Button><p className="privacy"><Check/>无需登录 · 仅记录匿名进度与结果摘要</p><div className="orb"><div className="orbit a"/><div className="orbit b"/><div className="core"><Compass/><b>10</b><span>项能力线索</span></div>{['表达','洞察','创想','逻辑','感知'].map((x,i)=><span className={`tag t${i}`} key={x}>{x}</span>)}</div></section><footer>本测试用于自我探索与娱乐参考；匿名记录访问进度与结果摘要，不收集姓名、手机号或逐题答案。</footer></main>;
 if(stage==='quiz'){const q=questions[current];return <main className="quiz-page"><nav><button className="back" onClick={()=>current?setCurrent(current-1):setStage('home')} aria-label="返回"><ArrowLeft/></button><div className="brand small"><span className="brand-mark">M</span>微光图谱</div><span className="counter">{String(current+1).padStart(2,'0')} / 30</span></nav><div className="progress"><span style={{width:`${(current+1)/30*100}%`}}/></div><section className="question"><p className="scene">情境 {String(current+1).padStart(2,'0')} · {q.scene}</p><h2>{q.title}</h2><p className="hint">选择最像你的第一反应，不必挑“更正确”的答案。</p><div className="options">{q.options.map((o,i)=><button key={i} className={answers[current]===i?'selected':''} onClick={()=>choose(i)}><span>{String.fromCharCode(65+i)}</span>{o.text}<ArrowRight/></button>)}</div></section><p className="save-note">进度会在本次浏览中自动保留</p></main>}
 const type=typeNames[(keys.indexOf(top[0].d[0])+keys.indexOf(top[1].d[0]))%typeNames.length];
 return <main className="result-page"><nav><div className="brand small"><span className="brand-mark">M</span>微光图谱</div><button className="restart" onClick={restart}><RotateCcw/>重新测试</button></nav><header className="result-hero"><p className="eyebrow">YOUR TALENT MAP · 个人报告</p><h1>你的天赋原型是<br/><em>「{type}」</em></h1><p>你最有力量的状态，是把 <b>{top[0].d[1]}</b>、<b>{top[1].d[1]}</b> 与 <b>{top[2].d[1]}</b> 连接起来：先看见细节，再形成自己的表达，最后把想法带进真实世界。</p><div className="top-three">{top.map((x,i)=><article key={x.d[0]}><span>TOP {i+1}</span><b>{x.d[1]}</b><strong>{x.score}</strong></article>)}</div></header><section className="report"><div className="chart-card"><p className="section-kicker">能力全景</p><h2>十维天赋图谱</h2><Radar values={scores}/><div className="score-list">{dims.map((d,i)=><div key={d[0]}><span>{d[1]}</span><i><b style={{width:`${scores[i]}%`,background:d[3]}}/></i><strong>{scores[i]}</strong></div>)}</div></div><div className="insight"><p className="section-kicker">核心优势</p><h2>{top[0].d[1]}，是你的第一驱动力</h2><p>{top[0].d[4]}当它与{top[1].d[1]}结合，你往往不仅能发现别人忽略的线索，还能让它们形成可行动的方案。</p><div className="mini"><span>潜在盲点</span><p>{top[0].d[5]}</p></div><div className="mini"><span>适合场景</span><p>{top[0].d[6]}</p></div></div><div className="career"><p className="section-kicker">职业方向不是答案，而是实验起点</p><h2>值得优先探索的方向</h2><div className="career-tags">{Array.from(new Set(top.flatMap(x=>x.d[7]))).slice(0,6).map((j,i)=><span key={j}>{String(i+1).padStart(2,'0')} · {j}</span>)}</div><p className="note">选择职业时，还需要结合兴趣、技能、价值观、现实机会与生活阶段综合判断。</p></div><div className="action"><p className="section-kicker">未来 7 天</p><h2>把天赋变成一个小证据</h2><ol><li><b>记录高光时刻</b><span>每天写下一件“做起来很自然”的小事。</span></li><li><b>设计一次微实验</b><span>从推荐方向里选一个，用 30 分钟做最小体验。</span></li><li><b>向可信的人求证</b><span>问两个人：我在哪类事情上特别有优势？</span></li></ol></div></section><footer className="result-footer"><p>这是一份探索邀请，不是一张人生判决书。</p><button onClick={()=>setStage('home')}>返回首页</button></footer></main>
}
