export type Key='self'|'people'|'create'|'aesthetic'|'language'|'logic'|'space'|'nature'|'body'|'music';
export type Option={text:string;scores:Partial<Record<Key,number>>};
export type Question={scene:string;title:string;options:Option[]};
const o=(text:string,a:Key,b?:Key):Option=>({text,scores:{[a]:3,...(b?{[b]:1}:{})}});
export const questions:Question[]=[
 {scene:'自由支配',title:'拥有一段完全由自己安排的时间，你最可能沉浸在哪件事里？',options:[o('编故事、写随笔，把想法组织成文字','language','create'),o('拆解规则、玩数字谜题或研究游戏胜法','logic','self'),o('画地图、搭模型，反复调整空间布局','space','aesthetic'),o('运动、做手工，在动作里忘记时间','body','create')]},
 {scene:'他人反馈',title:'熟悉你的人最可能因为什么肯定你？',options:[o('表达清楚，能把一件事讲得生动','language','people'),o('敏锐体贴，容易理解他人的感受','people','self'),o('点子很多，总能提出不一样的做法','create','logic'),o('很有眼光，搭配或画面总是舒服','aesthetic','space')]},
 {scene:'理想空间',title:'如果拥有一间完全属于自己的房间，你最想怎样使用它？',options:[o('分出不同区域，规划路线和收纳位置','space','logic'),o('种植植物，陈列来自自然的收藏','nature','aesthetic'),o('摆放乐器或声音设备，随时记录旋律','music','body'),o('留一处安静角落，整理自己的真实想法','self','language')]},
 {scene:'集体活动',title:'一群人暂时不知道做什么时，你更像哪一个？',options:[o('提出新玩法，把普通条件变得有趣','create','body'),o('制定清楚规则，安排顺序与分工','logic','people'),o('注意沉默的人，让每个人都能参与','people','self'),o('用一个故事或主题迅速调动气氛','language','space')]},
 {scene:'注意力漂移',title:'思绪暂时离开眼前任务时，它更容易飘向哪里？',options:[o('窗外的云、树影、动物和天气变化','nature','aesthetic'),o('周围的声音、节奏或一句旋律','music','language'),o('脑中浮现的画面、建筑或另一个世界','space','create'),o('自己此刻的感受，以及真正想做什么','self','logic')]},
 {scene:'自然收藏',title:'面对值得保存的东西，你更容易留下哪一类？',options:[o('有特殊形状的石头、树叶或自然资料','nature','logic'),o('漂亮纸张、色卡、照片和包装','aesthetic','create'),o('歌词、好句子、故事片段和信件','language','self'),o('零件、模型或能组装起来的小物件','body','space')]},
 {scene:'学习方式',title:'学习一件新事物时，哪种方式最容易让你迅速掌握？',options:[o('听别人讲一遍，再用自己的话复述','language','people'),o('先明白背后的规律和为什么','logic','self'),o('看图、看位置，在脑中把结构拼起来','space','aesthetic'),o('直接上手试，在动作反馈里调整','body','logic')]},
 {scene:'情绪雷达',title:'身边的气氛发生微妙变化时，你通常会怎样反应？',options:[o('很快察觉谁不舒服，并自然调整沟通方式','people','self'),o('暂时安静下来，辨认自己的感受与原因','self','language'),o('从语气、停顿或声响中听出不对劲','music','people'),o('去做一件具体的事，让气氛重新流动','body','create')]},
 {scene:'作品时刻',title:'完成一件作品时，什么最容易让你感到满足？',options:[o('它讲了一个别人愿意听下去的故事','language','people'),o('结构严密，每个部分都能对得上','logic','space'),o('它呈现了我自己的想法，不是在复制别人','create','self'),o('颜色、比例和细节看起来特别舒服','aesthetic','space')]},
 {scene:'忘记时间',title:'哪一种投入感，最容易让你暂时忘记时间？',options:[o('独自琢磨问题、复盘感受或写写画画','self','language'),o('与人深聊、组织活动或协调分歧','people','language'),o('听歌、打节拍、处理声音或反复哼唱','music','body'),o('在户外观察、照料植物或亲近动物','nature','body')]},
 {scene:'电影余韵',title:'看完一部好电影，什么会在你脑中停留最久？',options:[o('画面构图、服装和光影质感','aesthetic','space'),o('一句对白或人物如何讲述自己','language','self'),o('配乐进入的时机和情绪节奏','music','people'),o('角色选择背后的心理动机','people','self')]},
 {scene:'效率瓶颈',title:'重复工作越来越慢，你会怎样改变它？',options:[o('找出最耗时的节点，重新设计流程','logic','space'),o('尝试完全不同的工具或方法','create','logic'),o('亲手操作几遍，找到动作上的卡点','body','self'),o('观察自己在什么时候最容易分心','self','logic')]},
 {scene:'陌生聚会',title:'进入一个大多不认识人的聚会，你通常会？',options:[o('先观察谁和谁熟、现场是什么气氛','people','self'),o('找到一个话题，主动和身边的人聊起来','language','people'),o('注意音乐、灯光和空间带来的感受','aesthetic','music'),o('帮忙布置、递东西，让自己自然参与','body','people')]},
 {scene:'作品完成',title:'做完一个作品，哪一刻最令你满足？',options:[o('它呈现了一个只有我会想到的角度','create','self'),o('每个细节终于形成统一的气质','aesthetic','space'),o('实际使用时顺手、有效、经得住操作','body','logic'),o('别人准确理解了我想表达的东西','language','people')]},
 {scene:'一首新歌',title:'第一次听一首歌，你最先捕捉到什么？',options:[o('鼓点、速度以及身体想跟随的节拍','music','body'),o('声音营造出的颜色和画面感','aesthetic','space'),o('歌词怎样组织情绪和故事','language','self'),o('它让我想起了自己的哪段经历','self','music')]},
 {scene:'重要选择',title:'面对两个都不错的机会，你更信任什么？',options:[o('它是否符合我长期看重的东西','self','logic'),o('比较收益、代价和未来可能性','logic','space'),o('和了解我的人谈谈，听他们怎么看我','people','self'),o('哪个选择让我产生更多新设想','create','self')]},
 {scene:'模糊需求',title:'对方只说“做得高级一点”，你会怎么开始？',options:[o('找视觉案例，确认对方说的质感是什么','aesthetic','people'),o('追问使用场景、受众与真正目标','people','logic'),o('写出几种不同语气的表达让对方选择','language','create'),o('先做三个方向各异的快速样稿','create','body')]},
 {scene:'桌面整理',title:'整理一堆文件时，你更自然的方式是？',options:[o('按用途、频率和优先级建立规则','logic','self'),o('用位置和层级让结构一眼可见','space','aesthetic'),o('保留让我有情感或灵感的内容','self','create'),o('观察哪些内容已经过时或发生变化','nature','logic')]},
 {scene:'活动现场',title:'旁观一场活动，你最容易发现什么？',options:[o('谁被忽略了，谁在努力融入','people','self'),o('流程在哪里拥堵或让人困惑','logic','space'),o('场地动线是否自然、区域是否好找','space','body'),o('现场氛围为什么没有达到预期','aesthetic','music')]},
 {scene:'记忆方法',title:'要记住一段重要内容，哪种方式对你最有效？',options:[o('把它改写成自己的话并讲出来','language','self'),o('边走边背，配合动作或手势','body','music'),o('设置节拍、押韵或声音提示','music','language'),o('画成结构图并标记彼此位置','space','logic')]},
 {scene:'内容创作',title:'策划一条小红书内容时，你最想先做哪一步？',options:[o('找到一个意外但真实的切入角度','create','self'),o('想清标题和文字怎样抓住情绪','language','people'),o('确定封面色彩、版式和画面风格','aesthetic','space'),o('研究读者最常问什么、最担心什么','people','logic')]},
 {scene:'走进自然',title:'来到一片安静的树林，你最想做什么？',options:[o('观察植物、声音和季节留下的细节','nature','music'),o('沿着小路行走，用身体感受地形','body','space'),o('停下来辨认此刻内心的变化','self','nature'),o('拍下光影和色彩最动人的瞬间','aesthetic','create')]},
 {scene:'动手组装',title:'拿到一件需要组装的东西，你通常？',options:[o('先试着动手，在反馈里调整','body','logic'),o('先研究结构，想象每个部件的位置','space','logic'),o('仔细阅读说明，确认步骤没有歧义','language','logic'),o('想想能否改成更方便或有趣的样子','create','body')]},
 {scene:'解释概念',title:'怎样向别人说明一个复杂概念最像你？',options:[o('用一个准确的故事或生活比喻','language','create'),o('根据对方的表情及时换一种说法','people','language'),o('画出关系、层级和变化过程','space','logic'),o('直接示范一遍，让对方跟着操作','body','people')]},
 {scene:'恢复能量',title:'连续专注很久后，什么最能让你恢复？',options:[o('活动身体，让呼吸和肌肉重新舒展','body','self'),o('到户外看看树、天空或真实的远处','nature','aesthetic'),o('听几首熟悉的歌，让节奏带走疲惫','music','self'),o('独处一会，弄明白自己现在需要什么','self','nature')]},
 {scene:'体验评价',title:'第一次使用一个新产品，你最先判断什么？',options:[o('看起来是否协调，有没有独特气质','aesthetic','create'),o('功能逻辑是否清楚、操作是否高效','logic','body'),o('它有没有理解使用者的真实处境','people','self'),o('拿在手里是否自然，反馈是否及时','body','aesthetic')]},
 {scene:'临时发言',title:'突然被请上台讲两分钟，你最依靠什么？',options:[o('迅速找到一句核心观点组织语言','language','logic'),o('感受现场气氛，和听众建立连接','people','music'),o('回到真实体验，说出自己的判断','self','language'),o('用节奏、停顿和声音稳住全场','music','body')]},
 {scene:'趋势判断',title:'发现一个突然流行的趋势，你会如何判断它？',options:[o('找数据和反例，看它是否只是噪声','logic','self'),o('观察真实生活里哪些细节正在变化','nature','people'),o('听不同人如何谈论以及情绪从何而来','people','language'),o('思考能否把它重组为一个新方向','create','logic')]},
 {scene:'项目收尾',title:'合作项目结束时，你最在意留下什么？',options:[o('彼此仍然信任，下次愿意继续合作','people','self'),o('一套清楚、可复用的工作方法','logic','language'),o('一件完成度高、让人愿意展示的作品','aesthetic','create'),o('完整记录关键决定和经验教训','language','logic')]},
 {scene:'未来画面',title:'想象三年后的生活，哪个画面最让你期待？',options:[o('更了解自己，也能自主安排时间','self','nature'),o('持续创造有个人印记的作品','create','aesthetic'),o('与喜欢的人合作并真实影响他们','people','language'),o('搭建起一个稳定、高效运转的系统','logic','space')]},
];
